<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="TS_Insert" time="23" tests="1" failures="0" errors="1">
   <testsuite name="TS_Insert" tests="1" failures="0" errors="1" time="23" timestamp="2019-01-20 15:54:02" hostname="asalah - LPALXY0442.ejadaalex.local" id="Test Suites/Event Management/TS_Insert">
      <properties>
         <property name="deviceName" value=""/>
         <property name="devicePlatform" value=""/>
         <property name="logFolder" value="C:\\Users\\asalah\\git\\MOF\\Reports\\Event Management\\TS_Insert\\20190120_155358"/>
         <property name="logFiles" value="C:\\Users\\asalah\\git\\MOF\\Reports\\Event Management\\TS_Insert\\20190120_155358\\execution0.log"/>
         <property name="attachments" value=""/>
         <property name="hostName" value="asalah - LPALXY0442.ejadaalex.local"/>
         <property name="os" value="Windows 10 64bit"/>
         <property name="katalonVersion" value="5.10.1.1"/>
         <property name="browser" value="Chrome 71.0.3578.98"/>
         <property name="hostAddress" value="192.168.3.57"/>
         <property name="sessionId" value="d064dac76a89eb88edfd817dca36be8c"/>
         <property name="seleniumVersion" value="3.7.1"/>
         <property name="proxyInformation" value="ProxyInformation{proxyOption=NO_PROXY, proxyServerType=HTTP, password=, proxyServerAddress=, proxyServerPort=0}"/>
         <property name="platform" value="Windows 10"/>
      </properties>
      <testcase name="Test Cases/TC_Login" classname="Test Cases/TC_Login" status="PASSED">
         <system-out><![CDATA[2019-01-20 15:54:02 - [TEST_CASE][PASSED] - Test Cases/TC_Login: Test Cases/TC_Login

2019-01-20 15:54:03 - [TEST_STEP][PASSED] - pk_Functions.CS_Login.LoginFun(findTestObject(null), "http://192.168.0.190:8080/mof/#/", findTestObject("Login/Username"), findTestObject("Login/Password"), "AAttia", "123", findTestObject("Login/Login")): pk_Functions.CS_Login.LoginFun is PASSED

2019-01-20 15:54:03 - [MESSAGE][WARNING] - Test object id is null

2019-01-20 15:54:03 - [MESSAGE][INFO] - Starting 'Chrome' driver

2019-01-20 15:54:03 - [MESSAGE][INFO] - Action delay is set to 0 seconds

2019-01-20 15:54:23 - [MESSAGE][PASSED] - Browser is opened with url: 'http://192.168.0.190:8080/mof/#/'

2019-01-20 15:54:24 - [MESSAGE][PASSED] - Text 'AAttia' is set on object 'Object Repository/Login/Username'

2019-01-20 15:54:24 - [MESSAGE][PASSED] - Text '123' is set on object 'Object Repository/Login/Password'

2019-01-20 15:54:24 - [MESSAGE][PASSED] - Object: 'Object Repository/Login/Login' is clicked on

2019-01-20 15:54:24 - [MESSAGE][PASSED] - pk_Functions.CS_Login.LoginFun is PASSED]]></system-out>
         <system-err><![CDATA[]]></system-err>
      </testcase>
      <testcase name="Test Cases/Event Management/TC_Insert" classname="Test Cases/Event Management/TC_Insert" status="ERROR">
         <error type="ERROR" message="Test Cases/Event Management/TC_Insert FAILED.
Reason:
java.lang.IllegalArgumentException: Cannot find test data with id 'Data Files/EventManagement_ObjectRepository' because (of) 'java.lang.IllegalArgumentException: Test data with id 'Data Files/EventManagement_ObjectRepository' does not exist'
	at com.kms.katalon.core.testdata.TestDataFactory.findTestData(TestDataFactory.java:122)
	at com.kms.katalon.core.testdata.TestDataFactory$findTestData.callStatic(Unknown Source)
	at pk_Functions.CS_AllPageObject.AllPageObjectFun(CS_AllPageObject.groovy:53)
	at pk_Functions.CS_AllPageObject$AllPageObjectFun.call(Unknown Source)
	at pk_Functions.CS_AllPageData.AllPageDataFun(CS_AllPageData.groovy:60)
	at pk_Functions.CS_AllPageData.invokeMethod(CS_AllPageData.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at TC_Insert.run(TC_Insert:16)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:328)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:319)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:298)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:290)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:224)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestCaseMainPhase(TestSuiteExecutor.java:129)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:112)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:81)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:149)
	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
	at TempTestSuite1547992438523.run(TempTestSuite1547992438523.groovy:36)
"/>
         <system-out><![CDATA[2019-01-20 15:54:24 - [TEST_CASE][ERROR] - Test Cases/Event Management/TC_Insert: Test Cases/Event Management/TC_Insert FAILED.
Reason:
java.lang.IllegalArgumentException: Cannot find test data with id 'Data Files/EventManagement_ObjectRepository' because (of) 'java.lang.IllegalArgumentException: Test data with id 'Data Files/EventManagement_ObjectRepository' does not exist'
	at com.kms.katalon.core.testdata.TestDataFactory.findTestData(TestDataFactory.java:122)
	at com.kms.katalon.core.testdata.TestDataFactory$findTestData.callStatic(Unknown Source)
	at pk_Functions.CS_AllPageObject.AllPageObjectFun(CS_AllPageObject.groovy:53)
	at pk_Functions.CS_AllPageObject$AllPageObjectFun.call(Unknown Source)
	at pk_Functions.CS_AllPageData.AllPageDataFun(CS_AllPageData.groovy:60)
	at pk_Functions.CS_AllPageData.invokeMethod(CS_AllPageData.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at TC_Insert.run(TC_Insert:16)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:328)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:319)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:298)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:290)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:224)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestCaseMainPhase(TestSuiteExecutor.java:129)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:112)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:81)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:149)
	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
	at TempTestSuite1547992438523.run(TempTestSuite1547992438523.groovy:36)


2019-01-20 15:54:24 - [TEST_STEP][ERROR] - pk_Functions.CS_AllPageData.AllPageDataFun("EventManagement_ObjectRepository", "Sheet1", ["EventCode", "EventEnglishDescription", "EventArabicDescription", "EventGroup", "IsEnabled", "ValidFrom", "ValidTo"]): pk_Functions.CS_AllPageData.AllPageDataFun("EventManagement_ObjectRepository", "Sheet1", ["EventCode", "EventEnglishDescription", "EventArabicDescription", "EventGroup", "IsEnabled", "ValidFrom", "ValidTo"]) FAILED.
Reason:
java.lang.IllegalArgumentException: Cannot find test data with id 'Data Files/EventManagement_ObjectRepository' because (of) 'java.lang.IllegalArgumentException: Test data with id 'Data Files/EventManagement_ObjectRepository' does not exist'
	at com.kms.katalon.core.testdata.TestDataFactory.findTestData(TestDataFactory.java:122)
	at com.kms.katalon.core.testdata.TestDataFactory$findTestData.callStatic(Unknown Source)
	at pk_Functions.CS_AllPageObject.AllPageObjectFun(CS_AllPageObject.groovy:53)
	at pk_Functions.CS_AllPageObject$AllPageObjectFun.call(Unknown Source)
	at pk_Functions.CS_AllPageData.AllPageDataFun(CS_AllPageData.groovy:60)
	at pk_Functions.CS_AllPageData.invokeMethod(CS_AllPageData.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at TC_Insert.run(TC_Insert:16)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:328)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:319)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:298)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:290)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:224)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestCaseMainPhase(TestSuiteExecutor.java:129)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:112)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:81)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:149)
	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
	at TempTestSuite1547992438523.run(TempTestSuite1547992438523.groovy:36)


2019-01-20 15:54:25 - [MESSAGE][ERROR] - Cannot find test data with id 'Data Files/EventManagement_ObjectRepository' because (of) 'java.lang.IllegalArgumentException: Test data with id 'Data Files/EventManagement_ObjectRepository' does not exist'

2019-01-20 15:54:25 - [MESSAGE][ERROR] - pk_Functions.CS_AllPageData.AllPageDataFun("EventManagement_ObjectRepository", "Sheet1", ["EventCode", "EventEnglishDescription", "EventArabicDescription", "EventGroup", "IsEnabled", "ValidFrom", "ValidTo"]) FAILED.
Reason:
java.lang.IllegalArgumentException: Cannot find test data with id 'Data Files/EventManagement_ObjectRepository' because (of) 'java.lang.IllegalArgumentException: Test data with id 'Data Files/EventManagement_ObjectRepository' does not exist'
	at com.kms.katalon.core.testdata.TestDataFactory.findTestData(TestDataFactory.java:122)
	at com.kms.katalon.core.testdata.TestDataFactory$findTestData.callStatic(Unknown Source)
	at pk_Functions.CS_AllPageObject.AllPageObjectFun(CS_AllPageObject.groovy:53)
	at pk_Functions.CS_AllPageObject$AllPageObjectFun.call(Unknown Source)
	at pk_Functions.CS_AllPageData.AllPageDataFun(CS_AllPageData.groovy:60)
	at pk_Functions.CS_AllPageData.invokeMethod(CS_AllPageData.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at TC_Insert.run(TC_Insert:16)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:328)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:319)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:298)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:290)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:224)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestCaseMainPhase(TestSuiteExecutor.java:129)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:112)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:81)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:149)
	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
	at TempTestSuite1547992438523.run(TempTestSuite1547992438523.groovy:36)]]></system-out>
         <system-err><![CDATA[2019-01-20 15:54:24 - [TEST_CASE][ERROR] - Test Cases/Event Management/TC_Insert: Test Cases/Event Management/TC_Insert FAILED.
Reason:
java.lang.IllegalArgumentException: Cannot find test data with id 'Data Files/EventManagement_ObjectRepository' because (of) 'java.lang.IllegalArgumentException: Test data with id 'Data Files/EventManagement_ObjectRepository' does not exist'
	at com.kms.katalon.core.testdata.TestDataFactory.findTestData(TestDataFactory.java:122)
	at com.kms.katalon.core.testdata.TestDataFactory$findTestData.callStatic(Unknown Source)
	at pk_Functions.CS_AllPageObject.AllPageObjectFun(CS_AllPageObject.groovy:53)
	at pk_Functions.CS_AllPageObject$AllPageObjectFun.call(Unknown Source)
	at pk_Functions.CS_AllPageData.AllPageDataFun(CS_AllPageData.groovy:60)
	at pk_Functions.CS_AllPageData.invokeMethod(CS_AllPageData.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at TC_Insert.run(TC_Insert:16)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:328)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:319)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:298)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:290)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:224)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestCaseMainPhase(TestSuiteExecutor.java:129)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:112)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:81)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:149)
	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
	at TempTestSuite1547992438523.run(TempTestSuite1547992438523.groovy:36)]]></system-err>
      </testcase>
      <system-out><![CDATA[2019-01-20 15:54:02 - [TEST_SUITE][ERROR] - TS_Insert: Test Cases/Event Management/TC_Insert FAILED.
Reason:
java.lang.IllegalArgumentException: Cannot find test data with id 'Data Files/EventManagement_ObjectRepository' because (of) 'java.lang.IllegalArgumentException: Test data with id 'Data Files/EventManagement_ObjectRepository' does not exist'
	at com.kms.katalon.core.testdata.TestDataFactory.findTestData(TestDataFactory.java:122)
	at com.kms.katalon.core.testdata.TestDataFactory$findTestData.callStatic(Unknown Source)
	at pk_Functions.CS_AllPageObject.AllPageObjectFun(CS_AllPageObject.groovy:53)
	at pk_Functions.CS_AllPageObject$AllPageObjectFun.call(Unknown Source)
	at pk_Functions.CS_AllPageData.AllPageDataFun(CS_AllPageData.groovy:60)
	at pk_Functions.CS_AllPageData.invokeMethod(CS_AllPageData.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at TC_Insert.run(TC_Insert:16)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:328)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:319)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:298)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:290)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:224)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestCaseMainPhase(TestSuiteExecutor.java:129)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:112)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:81)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:149)
	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
	at TempTestSuite1547992438523.run(TempTestSuite1547992438523.groovy:36)]]></system-out>
      <system-err><![CDATA[2019-01-20 15:54:02 - [TEST_SUITE][ERROR] - TS_Insert: Test Cases/Event Management/TC_Insert FAILED.
Reason:
java.lang.IllegalArgumentException: Cannot find test data with id 'Data Files/EventManagement_ObjectRepository' because (of) 'java.lang.IllegalArgumentException: Test data with id 'Data Files/EventManagement_ObjectRepository' does not exist'
	at com.kms.katalon.core.testdata.TestDataFactory.findTestData(TestDataFactory.java:122)
	at com.kms.katalon.core.testdata.TestDataFactory$findTestData.callStatic(Unknown Source)
	at pk_Functions.CS_AllPageObject.AllPageObjectFun(CS_AllPageObject.groovy:53)
	at pk_Functions.CS_AllPageObject$AllPageObjectFun.call(Unknown Source)
	at pk_Functions.CS_AllPageData.AllPageDataFun(CS_AllPageData.groovy:60)
	at pk_Functions.CS_AllPageData.invokeMethod(CS_AllPageData.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at TC_Insert.run(TC_Insert:16)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:328)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:319)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:298)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:290)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:224)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestCaseMainPhase(TestSuiteExecutor.java:129)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:112)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:81)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:149)
	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
	at TempTestSuite1547992438523.run(TempTestSuite1547992438523.groovy:36)]]></system-err>
   </testsuite>
</testsuites>
